# Generated by Django 3.1 on 2020-09-09 23:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название бюджета')),
                ('budget_description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
                ('common_cost', models.FloatField(default=0, verbose_name='Общая сумма затрат')),
                ('balance', models.FloatField(default=0, verbose_name='Осталось средств')),
                ('my_funds', models.FloatField(default=0, verbose_name='Мои средства')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 23, 45, 19, 778913, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=255, verbose_name='На что потраченно')),
                ('amount_spent', models.FloatField(default=0, verbose_name='Потраченная сумма')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budget', verbose_name='Список бюджетов')),
            ],
        ),
        migrations.CreateModel(
            name='YearlySpend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_expense', models.FloatField(default=0, verbose_name='Годовая сумма затрат')),
                ('year_spend_date', models.DateField(default=2020, verbose_name='Год затртат')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budget', verbose_name='Бюджет')),
                ('yearly_budget_info', models.ManyToManyField(related_name='yearly_budget_info', to='budgets.BudgetData', verbose_name='Данные за год')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySpend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_expense', models.FloatField(default=0, verbose_name='Месячная сумма затрат')),
                ('month_spend_date', models.DateField(default=9, verbose_name='Месяц затрат')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budget', verbose_name='Бюджет')),
                ('monthly_budget_info', models.ManyToManyField(related_name='monthly_budget_info', to='budgets.BudgetData', verbose_name='Данные за месяц')),
            ],
        ),
        migrations.CreateModel(
            name='DailySpend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_expense', models.FloatField(default=0, verbose_name='Ежедневная сумма затрат')),
                ('today_spend_date', models.DateField(default=datetime.datetime(2020, 9, 9, 23, 45, 19, 780178, tzinfo=utc), verbose_name='День затрат')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budget', verbose_name='Бюджет')),
                ('today_budget_info', models.ManyToManyField(related_name='today_budget_info', to='budgets.BudgetData', verbose_name='Данные за сегодня')),
            ],
        ),
    ]
